spring:
  application:
    name: blog-back
  datasource:
    url: jdbc:postgresql://localhost:5432/blog-platform
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
jwt:
  secret: 9ae82b147c80f3c8250acae18958f96dd522b075aeda6864ab380d95b6be0bc5
